export const AUTH = 'AUTH';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL';
export const REAUTH = 'REAUTH';
export const REAUTH_START = 'REAUTH_START';
export const REAUTH_FAIL = 'REAUTH_FAIL';
export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const SET_SIGN_REDIRECT_PATH = 'SET_SIGN_REDIRECT_PATH';

export const ADD_ITEM = 'ADD_ITEM';
export const FETCHING_MY_ITEMS = 'FETCHING_MY_ITEMS';
export const FETCH_MY_ITEMS = 'FETCH_MY_ITEMS';
export const FETCH_MY_ITEMS_FAILED = 'FETCH_MY_ITEMS_FAILED';
export const DELETING_ITEM = 'DELETING_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_ITEM_FAILED = 'DELETE_ITEM_FAILED';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const UPDATING_ITEM = 'UPDATING_ITEM';
export const UPDATE_ITEM_FAILED = 'UPDATE_ITEM_FAILED';

export const FETCHING_FAVORITES = 'FETCHING_FAVORITES';
export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const FETCH_FAVORITES_FAILED = 'FETCH_FAVORITES_FAILED';

export const UNFAVORITE_ITEM = 'UNFAVORITE_ITEM';
export const FAVORITE_ITEM = 'FAVORITE_ITEM';
